Update ci.yml
added error handler for winston

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,6 +13,9 @@ jobs:
     runs-on: self-hosted # Runs on your local machine
 
     steps:
+      - name: Check installed modules
+        run: ls -l node_modules | grep winston || echo "winston is missing!"
+        
       - name: Install dependencies
         run: npm ci 
         
